# Generated by Django 3.1.4 on 2021-01-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
    ]
