# Generated by Django 3.1.4 on 2021-01-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_remove_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
